version: "3.9"

services:
  fb_postgres_db:
    image: postgres:16
    container_name: fb_postrges
    volumes:
      - ~/.pg/pg_data/fb:/var/lib/postgresql/data
    env_file:
      - .env
  fb_project_django:
    image: django:latest
    container_name: fb_django
    depends_on:
      - fb_postgres_db
    volumes:
      - static_volume:/fb/static
      - media_volume:/fb/media
    env_file:
      - .env
    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn -b 0.0.0.0:8000"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: fb_nginx
    image: fb_nginx
    volumes:
      - static_volume:/fb/static
      - media_volume:/fb/media
    depends_on:
      - fb_project_django
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"


volumes:
  static_volume:
  media_volume:

